### ISSUE TITLE
Double-check creation epo:EnvironmentalProtectionInformationProvider 

### ISSUE THREAD

**Issue by ahmadjana** [meaningfy-ws/eforms-mapping-artefacts#38]
Double-check why we create epo:EnvironmentalProtectionInformationProvider in both EnvironmentalProtectionInformationProvider.rml and technical_mapping_cn_v1.9.rml.ttl files. And Double-check if it exists for other roles

**Comment by schivmeister** [comment]
This has been superseded by many changes since and in particular deduplicated from technical_mapping_cn_v1.9 (now root) in [this commit](https://github.com/meaningfy-ws/eforms-mapping-artefacts/pull/56/commits/4e105c980024ba6b8f5fe42f77166c689ce026c9).
